#
set -g prefix C-x
unbind C-x
bind C-x send-prefix
#
set -g mouse on
set -g history-limit 10000
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
