#
# >> linux_display_server    x11
tab_bar_min_tabs        1
tab_bar_edge            bottom
tab_bar_style           powerline
tab_title_template      {index}: {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
#
font_family             Jetbrains Mono
bold_font               Jetbrains Mono Bold
italic_font             Jetbrains Mono Italic
bold_italic_font        Jetbrains Mono Bold Italic
#
font_size               9.0
